# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Daytona < Formula
  desc ""
  homepage "https://daytona.io/"
  version "2.0"

  on_macos do
    url "https://github.com/idagelic/TempDTN2/releases/download/v2.0/TempDTN2_2.0_darwin_all.tar.gz"
    sha256 "362e96350c5435778a7b0759784e86b0d4b1f1014ef689f0e02c31f08df27b58"

    def install
      bin.install "TempDTN2"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/idagelic/TempDTN2/releases/download/v2.0/TempDTN2_2.0_linux_arm64.tar.gz"
      sha256 "bb371d888b60d6f811bdc1021acea54e62c062b5ab02705b93de170188ae5348"

      def install
        bin.install "daytona"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/idagelic/TempDTN2/releases/download/v2.0/TempDTN2_2.0_linux_amd64.tar.gz"
      sha256 "bdd4c7d30d73d8409b6dc8542643ded031d99072526e4967af8f7024145aef49"

      def install
        bin.install "daytona"
      end
    end
  end
end
